### ISSUE TITLE
Issues caused by Packeta plugin

### ISSUE THREAD

**Issue by uhlhosting** [Zasilkovna/WooCommerce#248]
WordPress verze 6.0
Active theme: Mighty Lions (version 1.0)
Aktuální plugin: Packeta (verze 1.3.2)
Verze PHP 7.4.29

Podrobnosti chyby
=================
Na řádku č. 73 v souboru /home/mightylions/public_html/wp-content/plugins/packeta/src/Packetery/Module/Order/Controller.php došlo k chybě typu E_ERROR. Chybová zpráva: Uncaught ArgumentCountError: Too few arguments to function Packetery\Module\Order\Controller::__construct(), 4 passed in /home/mightylions/public_html/wp-content/plugins/packeta/temp/cache/nette.configurator/Container_de0590739c.php on line 365 and exactly 5 expected in /home/mightylions/public_html/wp-content/plugins/packeta/src/Packetery/Module/Order/Controller.php:73
Stack trace:
#0 /home/mightylions/public_html/wp-content/plugins/packeta/temp/cache/nette.configurator/Container_de0590739c.php(365): Packetery\Module\Order\Controller->__construct(Object(Packetery\Module\Order\Modal), Object(Packetery\Module\Order\ControllerRouter), Object(Packetery\Module\Order\PacketSubmitter), Object(Packetery\Module\Order\Repository))
#1 /home/mightylions/public_html/wp-content/plugins/packeta/packetery_vendor/nette/di/src/DI/Container.php(205): Container_de0590739c->createService031()
#2 /home/mightylions/public_html/wp-content/plugins/packeta/packetery_vendor/nette/di/src/DI/Container.php(121): PacketeryNette\DI\Contain

**Comment by uhlhosting** [comment]
The weirdest part is that it seems we are unable to remove the plugin either:

<img width="331" alt="image" src="https://user-images.githubusercontent.com/6324047/173884009-a3cfb797-e710-46d9-9ba2-108a8e839b14.png">

**Comment by uhlhosting** [comment]
I can confirm that deleting the plugin and reinstalling works, yet maybe something can be done to avoid this in future to crash entire site. Like it happened for one of our customers today.

**Comment by MatyasKoval** [comment]
Hello @uhlhosting ,
this definitely looks as if something went wrong during the installation, since even the uninstall was not working properly. 
Did you make an upgrade to the 1.3.2 version, or did you make a clean install?
If you were upgrading the plugin, from which version did you upgrade? 
We have tested the current version of the plugin in terms of installation etc. and we have not run into this issue, so we would like to try and pinpoint the cause of this error.

Best regards,
Matyáš Kovaľ - E-Commerce Support

**Comment by uhlhosting** [comment]
@MatyasKoval the issue returned this time maybe a bit different error message:

```
An error of type E_ERROR was caused in line 145 of the file /home/mightylions/public_html/wp-content/plugins/packeta/packetery_vendor/nette/component-model/src/ComponentModel/Container.php. Error message: Uncaught PacketeryNette\InvalidArgumentException: Component with name 'packetery_original_weight' does not exist. in /home/mightylions/public_html/wp-content/plugins/packeta/packetery_vendor/nette/component-model/src/ComponentModel/Container.php:145 Stack trace: #0 /home/mightylions/public_html/wp-content/plugins/packeta/packetery_vendor/nette/component-model/src/ComponentModel/ArrayAccess.php(40): PacketeryNette\ComponentModel\Container->getComponent('packetery_origi...') #1 /home/mightylions/public_html/wp-content/plugins/packeta/temp/cache/view/template-order-modal-template.latte--591defa085.php(50): PacketeryNette\Forms\Container->offsetGet('packetery_origi...') #2 /home/mightylions/public_html/wp-content/plugins/packeta/packetery_vendor/latte/latte/src/PacketeryLatte/Runtime/Template.php(173): Template591defa085->main() #3 /home/mightylions/public_html/wp-content/plugins/packeta/packetery_vendor/latte/latte/src/PacketeryLatte/Engine.php(101): PacketeryLatte\Runtime\Template->render(NULL) #4 /home/mightyl
```

**Comment by MatyasKoval** [comment]
Hello @uhlhosting, 
thank you for the update on the situation.
May I ask, are you installing new versions of our plugin from GitHub or directly from the wp.org installer? 
When updating, are you updating manually by installing the newest version from GitHub or are you updating automatically in WordPress?

The issue may be in the fact, that GitHub and wp.org versions may not be crosscompatible - a version from GitHub can cause issues when being updated directly in Wordpress.

Best regards,
Matyáš Kovaľ - E-Commerce Support

**Comment by uhlhosting** [comment]
> Hello @uhlhosting, 
> 
> thank you for the update on the situation.
> 
> May I ask, are you installing new versions of our plugin from GitHub or directly from the wp.org installer? 
> 
> When updating, are you updating manually by installing the newest version from GitHub or are you updating automatically in WordPress?
> 
> 
> 
> The issue may be in the fact, that GitHub and wp.org versions may not be crosscompatible - a version from GitHub can cause issues when being updated directly in Wordpress.
> 
> 
> 
> Best regards,
> 
> Matyáš Kovaľ - E-Commerce Support

Hi

It was always latest releases since issue were installed from wp repo.

**Comment by uhlhosting** [comment]
@MatyasKoval it seems the occurrences were quite random. Was not able until now to figure out the cause. I have migrated the client to a new server and another hosting panel. 

it seems at first Packeta had issues, I disabled and reenabled it seemed to have helped at least for now.

Will update this thread in case it reoccurs, if not will close it.
