### ISSUE TITLE
Fatal error: Uncaught Packetery\Module\Exception\DownloadException: cURL error 7

### ISSUE THREAD

**Issue by artemplaksiy** [Zasilkovna/WooCommerce#389]
Hi, WP admin stop working due to fatal error, see bellow. Can't add any more relevant info about the versions as the WEB UI is not accessible but I think that I allowed auto update for Zasilkovna plugin.
**UPDATE: affected version 1.5.0:**
![Screenshot from 2023-04-24 18-01-31](https://user-images.githubusercontent.com/34888588/234054371-b9ba21fe-ba8c-4b96-b625-6d4a7451655b.png)

```
[24-Apr-2023 15:39:02 UTC] PHP Fatal error:  Uncaught Packetery\Module\Exception\DownloadException: cURL error 7:  (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) in /data/www/25248/insta-moda_cz/www/wp-content/plugins/packeta/src/Packetery/Module/Options/FeatureFlagManager.php:95
Stack trace:
#0 /data/www/25248/insta-moda_cz/www/wp-content/plugins/packeta/src/Packetery/Module/Options/FeatureFlagManager.php(133): Packetery\Module\Options\FeatureFlagManager->fetchFlags()
#1 /data/www/25248/insta-moda_cz/www/wp-content/plugins/packeta/src/Packetery/Module/Options/FeatureFlagManager.php(170): Packetery\Module\Options\FeatureFlagManager->getFlags()
#2 /data/www/25248/insta-moda_cz/www/wp-content/plugins/packeta/src/Packetery/Module/Plugin.php(756): Packetery\Module\Options\FeatureFlagManager->isSplitActive()
#3 /data/www/25248/insta-moda_cz/www/wp-includes/class-wp-hook.php(308): Packetery\Module\Plugin->enqueueAdminAssets('index.php')
#4 /data/www/25248/insta-moda_cz/www/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array)
#5 /d in /data/www/25248/insta-moda_cz/www/wp-content/plugins/packeta/src/Packetery/Module/Options/FeatureFlagManager.php on line 95
```

**Comment by artemplaksiy** [comment]
"error 7" can be due to hosting provider Firewall settings, so I will try to allow the endpont frome here:
![image](https://user-images.githubusercontent.com/34888588/234051858-58727cee-838d-43b2-9cd0-3f91a2922e43.png)
, but anyway, this exception should be handled in some better way. Thank you!
