### ISSUE TITLE
Plugin po aktualizaci crashuje web

### ISSUE THREAD

**Issue by mlykotom** [Zasilkovna/WooCommerce#409]
Dobrý den,
po aktualizaci pluginu z verze 1.5.1 na 1.5.3 nám začal crashovat web s chybou níže.

Snažil jsem se  trochu dopátrat v čem je problém a vypadá to, že se změnily [parametry konstruktoru](https://github.com/Zasilkovna/WooCommerce/commit/a683ca81c237048c822545cda4b73e24f38e5c21#diff-940c08fc54d80c8dba7bdf8e1cd926d2d96abf88fe5c118c28f71c6855746b9dL65) `WidgetOptionsBuilder`.

Jelikož ale nette cache pro DI používala předchozí parametry, proto vznikla tato chyba.

Když jsme plugin smazali a nainstalovali znova, chyba zmizela (protože byla smazána nette cache).

**Moje otázka: používáte nějaký hook, který zkompilovanou cache promazává při updatu? Ať se zabrání podobné chybě v budoucnu?**

Děkuji

```
[12-May-2023 01:38:17 UTC] PHP Fatal error:  Uncaught TypeError: Packetery\Module\WidgetOptionsBuilder::__construct(): Argument #2 ($featureFlag) must be of type Packetery\Module\Options\FeatureFlagManager, Packetery\Module\RateCalculator given, called in /home/oqhmnhx/public_html/wp-content/plugins/packeta/temp/cache/nette.configurator/Container_d17f4fc4e9.php on line 679 and defined in /home/oqhmnhx/public_html/wp-content/plugins/packeta/src/Packetery/Module/WidgetOptionsBuilder.php:44
Stack trace:
#0 /home/oqhmnhx/public_html/wp-content/plugins/packeta/temp/cache/nette.configurator/Container_d17f4fc4e9.php(679): Packetery\Module\WidgetOptionsBuilder->__construct()
#1 /home/oqhmnhx/public_html/wp-content/plugins/packeta/packetery_vendor/nette/di/src/DI/Container.php(205): Container_d17f4fc4e9->createService059()
#2 /home/oqhmnhx/public_html/wp-content/plugins/packeta/packetery_vendor/nette/di/src/DI/Container.php(121): PacketeryNette\DI\Container->createService()
#3 /home/oqhmnhx/public_html/wp-content/plugins/packeta/temp/cache/nette.configurator/Container_d17f4fc4e9.php(213): PacketeryNette\DI\Container->getService()
#4 /home/oqhmnhx/public_html/wp-content/plugins/packeta/packetery_vendor/nette/di/src/DI/Container.php(205): Container_d17f4fc4e9->createService013()
#5 /home/oqhmnhx/public_html/wp-content/plugins/packeta/packetery_vendor/nette/di/src/DI/Container.php(121): PacketeryNette\DI\Container->createService()
#6 /home/oqhmnhx/public_html/wp-content/plugins/packeta/temp/cache/nette.configurator/Container_d17f4fc4e9.php(221): PacketeryNette\DI\Container->getService()
#7 /home/oqhmnhx/public_html/wp-content/plugins/packeta/packetery_vendor/nette/di/src/DI/Container.php(205): Container_d17f4fc4e9->createService014()
#8 /home/oqhmnhx/public_html/wp-content/plugins/packeta/packetery_vendor/nette/di/src/DI/Container.php(121): PacketeryNette\DI\Container->createService()
#9 /home/oqhmnhx/public_html/wp-content/plugins/packeta/packetery_vendor/nette/di/src/DI/Container.php(230): PacketeryNette\DI\Container->getService()
#10 /home/oqhmnhx/public_html/wp-content/plugins/packeta/packeta.php(38): PacketeryNette\DI\Container->getByType()
#11 /home/oqhmnhx/public_html/wp-settings.php(453): include_once('/home/oqhmnhx/p...')
#12 /home/oqhmnhx/public_html/wp-config.php(114): require_once('/home/oqhmnhx/p...')
#13 /home/oqhmnhx/public_html/wp-load.php(50): require_once('/home/oqhmnhx/p...')
#14 /home/oqhmnhx/public_html/wp-blog-header.php(13): require_once('/home/oqhmnhx/p...')
#15 /home/oqhmnhx/public_html/index.php(17): require('/home/oqhmnhx/p...')
#16 {main}
  thrown in /home/oqhmnhx/public_html/wp-content/plugins/packeta/src/Packetery/Module/WidgetOptionsBuilder.php on line 44
```

**Comment by MatyasKoval** [comment]
Dobrý den @mlykotom,
Děkuji za nahlášení tohoto chování.
Při instalaci z wp.org se přepíše celý adresář pluginu a tím dojde automaticky i k promazání cache.  
Jak konkrétně provádíte aktualizaci pluginu vy ? 

S pozdravem,
Matyáš Kovaľ - Zásilkovna E-Commerce Support

**Comment by mlykotom** [comment]
Meli jsme nastavenou automatickou aktualizaci pluginu u hostingu. Mozna, ze oni to delaji nejak jinak, ale nejsem si jisty.

Jestli oficialni způsob funguje takto, tak možná není problém. Jen jsem to chtěl ověřit, že tam není nějaký zapomenutý problém.

Díky
