### ISSUE TITLE
Version 1.7.2 Uncaught ServiceCreationException

### ISSUE THREAD

**Issue by dbydzovsky** [Zasilkovna/WooCommerce#534]
Dobrý den, 

po automatickém upgradu na verzi 1.7.2 mi přestal fungovat wordpress. Vyřešil jsem downgradem na 1.7.1 a opět funguji. Chybě vůbec nerozumím, ani proč se tak děje. Doufám, že chybu zakládám správně. Dyštak dodám další detaily, pokud bude potřeba :) 

Verze 1.7.2 | Autor: Zásilkovna s.r.o. | View details
 Tento plugin se nepodařilo správně načíst a během režimu obnovení byl pozastaven.

```php
Na řádku č. 110 v souboru /data/a/7/xxxxxxxxxxx-xxxxx-xxxx-xxxx/example.cz/web/wp-content/plugins/packeta/deps/nette/di/src/DI/Resolver.php došlo k chybě typu E_ERROR. Chybová zpráva: Uncaught Packetery\Nette\DI\ServiceCreationException: Service (Packetery\Module\ShippingZoneRepository::__construct()): Class Packetery\Module\ShippingZoneRepository not found. in /data/a/7/xxxxxxxxxxx-xxxxx-xxxx-xxxx/example.cz/web/wp-content/plugins/packeta/deps/nette/di/src/DI/Resolver.php:110 Stack trace: #0 /data/a/7/xxxxxxxxxxx-xxxxx-xxxx-xxxx/example.cz/web/wp-content/plugins/packeta/deps/nette/di/src/DI/Definitions/ServiceDefinition.php(141): Packetery\Nette\DI\Resolver->resolveEntityType(Object(Packetery\Nette\DI\Definitions\Statement)) #1 /data/a/7/xxxxxxxxxxx-xxxxx-xxxx-xxxx/example.cz/web/wp-content/plugins/packeta/deps/nette/di/src/DI/Resolver.php(55): Packetery\Nette\DI\Definitions\ServiceDefinition->resolveType(Object(Packetery\Nette\DI\Resolver)) #2 /data/a/7/xxxxxxxxxxx-xxxxx-xxxx-xxxx/example.cz/web/wp-content/plugins/packeta/deps/nette/di/src/DI/ContainerBuilder.php(232): Packetery\Nette\DI\Resolver->resolveDefinition(Object(Packetery\Nette\DI\Definitions\ServiceDefinition)) #3 /data/a/7/xxxxxxxxxxx-xxxxx-xxxx-xxxx/example.cz/web/wp-content/plugins/packeta/deps/nette/di/src/DI/Compiler.php(200): Packetery\Nette\DI\ContainerBuilder->resolve() #4 /data/a/7/xxxxxxxxxxx-xxxxx-xxxx-xxxx/example.cz/web/wp-content/plugins/packeta/deps/nette/di/src/DI/Compiler.php(160): Packetery\Nette\DI\Compiler->processBeforeCompile() #5 /data/a/7/xxxxxxxxxxx-xxxxx-xxxx-xxxx/example.cz/web/wp-content/plugins/packeta/deps/nette/di/src/DI/ContainerLoader.php(100): Packetery\Nette\DI\Compiler->compile() #6 /data/a/7/xxxxxxxxxxx-xxxxx-xxxx-xxxx/example.cz/web/wp-content/plugins/packeta/deps/nette/di/src/DI/ContainerLoader.php(66): Packetery\Nette\DI\ContainerLoader->generate('Container_b8a07...', Array) #7 /data/a/7/xxxxxxxxxxx-xxxxx-xxxx-xxxx/example.cz/web/wp-content/plugins/packeta/deps/nette/di/src/DI/ContainerLoader.php(35): Packetery\Nette\DI\ContainerLoader->loadFile('Container_b8a07...', Array) #8 /data/a/7/xxxxxxxxxxx-xxxxx-xxxx-xxxx/example.cz/web/wp-content/plugins/packeta/deps/nette/bootstrap/src/Bootstrap/Configurator.php(190): Packetery\Nette\DI\ContainerLoader->load(Array, Array) #9 /data/a/7/xxxxxxxxxxx-xxxxx-xxxx-xxxx/example.cz/web/wp-content/plugins/packeta/deps/nette/bootstrap/src/Bootstrap/Configurator.php(176): Packetery\Nette\Bootstrap\Configurator->loadContainer() #10 /data/a/7/xxxxxxxxxxx-xxxxx-xxxx-xxxx/example.cz/web/wp-content/plugins/packeta/bootstrap.php(42): Packetery\Nette\Bootstrap\Configurator->createContainer() #11 /data/a/7/xxxxxxxxxxx-xxxxx-xxxx-xxxx/example.cz/web/wp-content/plugins/packeta/packeta.php(37): require('/data/a/7/a7db9...') #12 /data/a/7/xxxxxxxxxxx-xxxxx-xxxx-xxxx/example.cz/web/wp-settings.php(517): include_once('/data/a/7/a7db9...') #13 /data/a/7/xxxxxxxxxxx-xxxxx-xxxx-xxxx/example.cz/web/wp-config.php(93): require_once('/data/a/7/a7db9...') #14 /data/a/7/xxxxxxxxxxx-xxxxx-xxxx-xxxx/example.cz/web/wp-load.php(50): require_once('/data/a/7/a7db9...') #15 /data/a/7/xxxxxxxxxxx-xxxxx-xxxx-xxxx/example.cz/web/wp-login.php(12): require('/data/a/7/a7db9...') #16 {main} thrown
```

Díky :)

**Comment by MatyasKoval** [comment]
Dobrý den @dbydzovsky,
omlouvám se za pozdní reakci.

Mohl bych poprosit jednak o zaslání exportu natavení z našeho pluginu na adresu e-commerce.support@packeta.com ? Export jde provést skrze Zásilkovna->Nastavení, sekce Podpora. V tomto exportu jsou vidět informace jako například verze PHP, WP, WooCommerce a další, které by mohly mít za důsledek problém při instalaci.

Druhak bychom potřebovali vědět, instaloval jste plugin manuálně za pomoci souboru z GitHubu, nebo jste aktualizaci prováděl skrze klasické aktualizace WordPressu?

S pozdravem,
Matyáš Kovaľ - Packeta E-Commerce Support
